export const openapi = {
  openapi: '3.0.3',
  info: { title: 'GhostOps API', version: '1.0.0', description: 'Autonomous AI operations agent — intake, incidents, approvals, audit.' },
  servers: [{ url: '/api/v1' }],
  tags: [
    { name: 'Ingest' },
    { name: 'Incidents' },
    { name: 'Approvals' },
    { name: 'Auth' },
    { name: 'Integrations' },
    { name: 'Audit' },
    { name: 'System' },
  ],
  paths: {
    '/incidents': {
      post: { tags: ['Ingest'], summary: 'Ingest an incident (API key with ingest scope)', operationId: 'ingestIncident', security: [{ bearerAuth: [] }], requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['title', 'issue'], properties: { title: { type: 'string' }, issue: { type: 'string' }, severity: { type: 'string', enum: ['critical', 'high', 'medium', 'low'] }, transactionId: { type: 'string' }, affectedService: { type: 'string' }, customer: { type: 'object' }, metadata: { type: 'object' } } } } } }, responses: { 201: { description: 'Incident created and agent queued' }, 503: { description: 'Intake refused' } } },
      get: { tags: ['Incidents'], summary: 'List incidents', operationId: 'listIncidents', security: [{ cookieAuth: [] }], parameters: [{ name: 'status', in: 'query', schema: { type: 'string' } }, { name: 'severity', in: 'query', schema: { type: 'string' } }, { name: 'q', in: 'query', schema: { type: 'string' } }, { name: 'limit', in: 'query', schema: { type: 'integer' } }, { name: 'offset', in: 'query', schema: { type: 'integer' } }], responses: { 200: { description: 'Paged incidents' } } },
    },
    '/incidents/stats': { get: { tags: ['Incidents'], summary: 'Analytics aggregates', operationId: 'incidentStats', security: [{ cookieAuth: [] }], responses: { 200: { description: 'Stats' } } } },
    '/incidents/{id}': { get: { tags: ['Incidents'], summary: 'Incident detail with events/actions/approvals/runs', operationId: 'getIncident', security: [{ cookieAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'Facts' }, 404: { description: 'Not found' } } } },
    '/incidents/{id}/actions': { get: { tags: ['Incidents'], summary: 'Actions for incident', operationId: 'listActions', security: [{ cookieAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'Actions' } } }, post: { tags: ['Incidents'], summary: 'Submit an action manually', operationId: 'submitAction', security: [{ cookieAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 201: { description: 'Action submitted or approval raised' } } } },
    '/incidents/{id}/reinvestigate': { post: { tags: ['Incidents'], summary: 'Re-run the agent for an incident', operationId: 'reinvestigate', security: [{ cookieAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'Queued' } } } },
    '/incidents/{id}/cancel': { post: { tags: ['Incidents'], summary: 'Cancel an incident', operationId: 'cancelIncident', security: [{ cookieAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'Cancelled' } } } },
    '/incidents/approvals/{approvalId}': { post: { tags: ['Approvals'], summary: 'Approve or reject a pending approval', operationId: 'decideApproval', security: [{ cookieAuth: [] }], parameters: [{ name: 'approvalId', in: 'path', required: true, schema: { type: 'string' } }], requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['decision'], properties: { decision: { type: 'string', enum: ['approved', 'rejected'] }, reason: { type: 'string' } } } } } }, responses: { 200: { description: 'Decided' }, 409: { description: 'Already decided or expired' } } } },
    '/auth/login': { post: { tags: ['Auth'], summary: 'Sign in with email + password', operationId: 'login', responses: { 200: { description: 'Session cookie set' } } } },
    '/auth/logout': { post: { tags: ['Auth'], summary: 'Sign out', operationId: 'logout', responses: { 200: { description: 'Cleared' } } } },
    '/auth/me': { get: { tags: ['Auth'], summary: 'Current user', operationId: 'me', responses: { 200: { description: 'User' } } } },
    '/auth/users': { get: { tags: ['Auth'], summary: 'List users (admin)', operationId: 'listUsers', responses: { 200: { description: 'Users' } } }, post: { tags: ['Auth'], summary: 'Create user (admin)', operationId: 'createUser', responses: { 201: { description: 'Created' } } } },
    '/auth/api-keys': { get: { tags: ['Auth'], summary: 'List API keys', operationId: 'listApiKeys', responses: { 200: { description: 'Keys' } } }, post: { tags: ['Auth'], summary: 'Create API key', operationId: 'createApiKey', responses: { 201: { description: 'Key (secret shown once)' } } } },
    '/webhooks/payment': { post: { tags: ['Integrations'], summary: 'Payment provider webhook (HMAC)', operationId: 'paymentWebhook', responses: { 201: { description: 'Accepted' }, 503: { description: 'Rejected — not configured/invalid signature' } } } },
    '/webhooks/booking': { post: { tags: ['Integrations'], summary: 'Booking provider webhook (HMAC)', operationId: 'bookingWebhook', responses: { 201: { description: 'Accepted' }, 503: { description: 'Rejected' } } } },
    '/webhooks/monitoring': { post: { tags: ['Integrations'], summary: 'Monitoring webhook (HMAC)', operationId: 'monitoringWebhook', responses: { 201: { description: 'Accepted' }, 503: { description: 'Rejected' } } } },
    '/webhooks/support': { post: { tags: ['Integrations'], summary: 'Support ticket webhook (HMAC)', operationId: 'supportWebhook', responses: { 201: { description: 'Accepted' }, 503: { description: 'Rejected' } } } },
    '/integrations': { get: { tags: ['Integrations'], summary: 'Integration registry + health', operationId: 'listIntegrations', responses: { 200: { description: 'Integrations' } } } },
    '/audit': { get: { tags: ['Audit'], summary: 'Audit log (paged)', operationId: 'listAudit', parameters: [{ name: 'action', in: 'query', schema: { type: 'string' } }, { name: 'limit', in: 'query', schema: { type: 'integer' } }, { name: 'offset', in: 'query', schema: { type: 'integer' } }], responses: { 200: { description: 'Entries' } } } },
    '/outbox': { get: { tags: ['Integrations'], summary: 'Outbox state', operationId: 'listOutbox', responses: { 200: { description: 'Messages' } } } },
    '/health': { get: { tags: ['System'], summary: 'Liveness', operationId: 'health', responses: { 200: { description: 'ok' } } } },
    '/ready': { get: { tags: ['System'], summary: 'Readiness', operationId: 'readiness', responses: { 200: { description: 'ready' }, 503: { description: 'not ready' } } } },
    '/metrics': { get: { tags: ['System'], summary: 'Prometheus metrics', operationId: 'metrics', responses: { 200: { description: 'text' } } } },
    '/openapi.json': { get: { tags: ['System'], summary: 'This document', operationId: 'openapiJson', responses: { 200: { description: 'spec' } } } },
  },
  components: {
    securitySchemes: {
      cookieAuth: { type: 'apiKey', in: 'cookie', name: 'ghostops_session' },
      bearerAuth: { type: 'http', scheme: 'bearer' },
    },
  },
};